qualifiers_database = {
    "AB": "Abnormalities",
    "AD": "Administration & Dosage",
    "AE": "Adverse Effects",
    "AG": "Agonists",
    "AA": "Analogs & Derivatives",
    "AN": "Analysis",
    "AH": "Anatomy & Histology",
    "AI": "Antagonists & Inhibitors",
    "BI": "Biosynthesis",
    "BL": "Blood",
    "BS": "Blood Supply",
    "CF": "Cerebrospinal Fluid",
    "CS": "Chemical Synthesis",
    "CI": "Chemically Induced",
    "CH": "Chemistry",
    "CL": "Classification",
    "CO": "Complications",
    "CN": "Congenital",
    "CY": "Cytology",
    "DF": "Deficiency",
    "DI": "Diagnosis",
    "DG": "Diagnostic Imaging",
    "DH": "Diet Therapy",
    "DE": "Drug Effects",
    "DT": "Drug Therapy",
    "EC": "Economics",
    "ED": "Education",
    "EM": "Embryology",
    "EN": "Enzymology",
    "EP": "Epidemiology",
    "ES": "Ethics",
    "EH": "Ethnology",
    "ET": "Etiology",
    "GE": "Genetics",
    "GD": "Growth & Development",
    "HI": "History",
    "IM": "Immunology",
    "IN": "Injuries",
    "IR": "Innervation",
    "IS": "Instrumentation",
    "IP": "Isolation & Purification",
    "LJ": "Legislation & Jurisprudence",
    "ME": "Metabolism",
    "MT": "Methods",
    "MI": "Microbiology",
    "MO": "Mortality",
    "NU": "Nursing",
    "OG": "Organization & Administration",
    "PS": "Parasitology",
    "PY": "Pathogenicity",
    "PA": "Pathology",
    "PK": "Pharmacokinetics",
    "PD": "Pharmacology",
    "PH": "Physiology",
    "PP": "Physiopathology",
    "PO": "Poisoning",
    "PC": "Prevention & Control",
    "PX": "Psychology",
    "RE": "Radiation Effects",
    "RT": "Radiotherapy",
    "RH": "Rehabilitation",
    "SC": "Secondary",
    "ST": "Standards",
    "SN": "Statistics & Numerical Data",
    "SD": "Supply & Distribution",
    "SU": "Surgery",
    "TU": "Therapeutic Use",
    "TH": "Therapy",
    "TO": "Toxicity",
    "TM": "Transmission",
    "TR": "Transplantation",
    "TD": "Trends",
    "UL": "Ultrastructure",
    "UR": "Urine",
    "VE": "Veterinary",
    "VI": "Virology"
}
